### ISSUE TITLE
Getting error on home

### ISSUE THREAD

**Issue by saiftheboss7** [kroos/laravel-invoice#1]
I downloaded the project on pc. Did composer install and npm install. I could log in but could not get the homepage working. It is giving me this error.

https://i.imgur.com/tEASUgG.png

**Comment by saiftheboss7** [comment]
```
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'invoice_product.color' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select name, color from 
                                (SELECT
                                    `users`.`name` AS `name`,
                                    `users`.`color` AS `color`,
                                    `sales`.`id` AS `id`,
                                    `sales`.`date_sale` AS `date_sale`,
                                    `products`.`product` AS `product`,
                                    `sales_items`.`commission` AS `commission`,
                                    `sales_items`.`retail` AS `retail`,
                                    `sales_items`.`quantity` AS `quantity`,
                                    round((`sales_items`.`retail` * `sales_items`.`quantity`),2) AS `TotalAmount`,
                                    round((`sales_items`.`commission` * `sales_items`.`quantity`),2)AS `TotalCommission`,
                                    `taxes`.`tax` AS `tax`,
                                    ifnull(`taxes`.`amount`, 0)AS `tax_charges`,
                                    round((round((`sales_items`.`retail` * `sales_items`.`quantity`),2)*(ifnull(`taxes`.`amount`, 0)/ 100)),2)AS `TotalTax`,
                                    (round((`sales_items`.`retail` * `sales_items`.`quantity`),2) + round((round((`sales_items`.`retail` * `sales_items`.`quantity`),2)*(ifnull(`taxes`.`amount`, 0)/ 100)),2))AS `GrandTotal`
                                FROM
                                    (
                                        (
                                            (
                                                (
                                                    (
                                                        (
                                                            (`sales` JOIN `sales_items` ON((`sales_items`.`id_sales` = `sales`.`id`)))
                                                            JOIN `products` ON((`sales_items`.`id_product` = `products`.`id`)))
                                                        LEFT JOIN `users` ON((`sales`.`id_user` = `users`.`id`)))
                                                    LEFT JOIN `sales_taxes` ON((`sales_taxes`.`id_sales` = `sales`.`id`)))
                                                LEFT JOIN `taxes` ON((`taxes`.`id` = `sales_taxes`.`id_tax`)))
                                            LEFT JOIN `sales_customers` ON((`sales_customers`.`id_sales` = `sales`.`id`)))
                                        LEFT JOIN `customers` ON((`customers`.`id` = `sales_customers`.`id_customer`)))
                                WHERE
                                    (
                                        ISNULL(`sales`.`deleted_at`)
                                        AND ISNULL(`sales_items`.`deleted_at`)
                                        AND ISNULL(`sales_taxes`.`deleted_at`)
                                        AND ISNULL(`sales_customers`.`deleted_at`)
                                    )
                                ) AS invoice_product
                         where year(`date_sale`) = 2019 group by `name`) (View: E:\laravel-invoice-master\resources\views\homeauth\home.blade.php)
```

**Comment by kroos** [comment]
> 
> 
> I downloaded the project on pc. Did composer install and npm install. I could log in but could not get the homepage working. It is giving me this error.
> 
> https://i.imgur.com/tEASUgG.png

hi there,
its because u didnt setup ur database correctly. please check ur database server and ur .env file.

**Comment by saiftheboss7** [comment]
Well I did setup my db server correctly. If I hadn't then I wouldn't get the login page and do login with the username dhiauddin. If I give wrong pass/username - can't login. Once I give correct pass - I am shown this.

I tried using old mysql server (5.5/5.6) to test if it was the db issue. It wasn't. The error persisted. Am I missing something?

Could you test this on localhost using Xamp/WAMP?

**Comment by kroos** [comment]
>  error or access violation: 1055 Expression

hi saif,
in the main folder there are 2 database files. please restore the database from tribas_invoice.sql and then try to login with this credentials
user : dhiauddin
password : 123123

if u still having a problem, please post it here. thank you

**Comment by saiftheboss7** [comment]
Yes. I restored that database. I get to the login page. Login works. But after login when it goes to /home, I get this error.

The error is the first post with image

**Comment by kroos** [comment]
hi saif, try use these:

i get it from here : https://stackoverflow.com/questions/36950857/sqlstate42000-syntax-error-or-access-violation-1055-expression-3-of-select

Another way would be using the MySQL configs. Go to my.cnf:

    add a section for [mysqld] and right below it add the statement sql_mode = ""

    restart the mysql service

**Comment by kroos** [comment]
> 
> 
> Getting this error on /home after login.
> 
> ```
> SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'invoice_product.color' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select name, color from 
>                                 (SELECT
>                                     `users`.`name` AS `name`,
>                                     `users`.`color` AS `color`,
>                                     `sales`.`id` AS `id`,
>                                     `sales`.`date_sale` AS `date_sale`,
>                                     `products`.`product` AS `product`,
>                                     `sales_items`.`commission` AS `commission`,
>                                     `sales_items`.`retail` AS `retail`,
>                                     `sales_items`.`quantity` AS `quantity`,
>                                     round((`sales_items`.`retail` * `sales_items`.`quantity`),2) AS `TotalAmount`,
>                                     round((`sales_items`.`commission` * `sales_items`.`quantity`),2)AS `TotalCommission`,
>                                     `taxes`.`tax` AS `tax`,
>                                     ifnull(`taxes`.`amount`, 0)AS `tax_charges`,
>                                     round((round((`sales_items`.`retail` * `sales_items`.`quantity`),2)*(ifnull(`taxes`.`amount`, 0)/ 100)),2)AS `TotalTax`,
>                                     (round((`sales_items`.`retail` * `sales_items`.`quantity`),2) + round((round((`sales_items`.`retail` * `sales_items`.`quantity`),2)*(ifnull(`taxes`.`amount`, 0)/ 100)),2))AS `GrandTotal`
>                                 FROM
>                                     (
>                                         (
>                                             (
>                                                 (
>                                                     (
>                                                         (
>                                                             (`sales` JOIN `sales_items` ON((`sales_items`.`id_sales` = `sales`.`id`)))
>                                                             JOIN `products` ON((`sales_items`.`id_product` = `products`.`id`)))
>                                                         LEFT JOIN `users` ON((`sales`.`id_user` = `users`.`id`)))
>                                                     LEFT JOIN `sales_taxes` ON((`sales_taxes`.`id_sales` = `sales`.`id`)))
>                                                 LEFT JOIN `taxes` ON((`taxes`.`id` = `sales_taxes`.`id_tax`)))
>                                             LEFT JOIN `sales_customers` ON((`sales_customers`.`id_sales` = `sales`.`id`)))
>                                         LEFT JOIN `customers` ON((`customers`.`id` = `sales_customers`.`id_customer`)))
>                                 WHERE
>                                     (
>                                         ISNULL(`sales`.`deleted_at`)
>                                         AND ISNULL(`sales_items`.`deleted_at`)
>                                         AND ISNULL(`sales_taxes`.`deleted_at`)
>                                         AND ISNULL(`sales_customers`.`deleted_at`)
>                                     )
>                                 ) AS invoice_product
>                          where year(`date_sale`) = 2019 group by `name`) (View: E:\laravel-invoice-master\resources\views\homeauth\home.blade.php)
> ```
or u could use this :
https://stackoverflow.com/questions/40917189/laravel-syntax-error-or-access-violation-1055-error

**Comment by saiftheboss7** [comment]
I guess since it's your project it would be really awesome if you could rewrite that portion so that the pages are compatible for most of us.
